### PR TITLE
Extension for retrieving company profile info

### PR DESCRIPTION
**Pull request by rmourato**
Hi folks,

First of all thanks for making this library available!

My use case for using the Companies House API was for retrieving details of a specific company (given it's number) rather than a generic search. Instead of rolling out my own thing I thought about extending your library to do this.

My proposed changes are an extension to your API to offer the request to `GET /company/{company_number}` and deserialize the response to the appropriate POCO, a `CompanyProfile` object.
The new method signature for this is `Task<CompaniesHouseClientResponse<CompanyProfile>> GetCompanyProfileAsync(string companyNumber, CancellationToken cancellationToken = default(CancellationToken));`

I kept the implementation in-line with yours so hopefully you should see no surprises, and I made no changes to existing code apart from moving a few common types around for reuse.

I might further extend this later (I have the `officerList `in mind to do next) but thought I'd put this forward for early review.

### CODE REVIEW

**Comment by kevbite** [comment]
Hello,
Contributions are always welcome and it's great to see people helping out with the OSS community.

A quick review of the code - It looks great and keeps in line with the rest of the coding styles within the project.

If you could just update the version to the next minor (1.2.0) within the appveyor.yml we'll get that merged in and pushed to nuget.

Thanks

LiberisLabs

**Comment by rmourato** [comment]
Hi Kevin,

Thanks for the quick reply.
The version has been updated and build looks green now.

Cheers,
Rui

**Comment by kevbite** [comment]
It's all merge in now and pushed to nuget, we've had to bump up the version again to 1.2.1 due to appveyor but fixed this issue for next time round.

http://www.nuget.org/packages/CompaniesHouse/1.2.1

**Comment by rmourato** [comment]
Thanks Kevin.
I'll have the version in mind if I submit another PR.

**Pull request merged**
