### PR TITLE
re-target for .NET 4.5 (temporary)

### LINKED ISSUE #9: Targeting Hell
Unfortunately my clients are using various versions of .NET and this library only targets 4.5.1.

This issue is to create targets for 4.5, 4.6, and Core (at least).

All files to be included in a single nuget package.

References:
http://blog.marcgravell.com/2015/11/the-road-to-dnxpart-3.html
https://stackoverflow.com/questions/34611829/how-to-package-a-net-framework-library

### PR DESCRIPTION
**Pull request by turowicz**
Resolves #9

### CODE REVIEW

**Comment by kevbite** [comment]
You need to retarget all the nuget packages with
```
Update-Package -reinstall
```
As there's still all pointing to 451

**Comment by kevbite** [comment]
https://docs.nuget.org/consume/reinstalling-packages

**Comment by turowicz** [comment]
on it

**Comment by turowicz** [comment]
done :) sorry for that - rookie error.

**Comment by kevbite** [comment]
No worries done that mistake before. 

Merging in.

**Pull request merged**
