### PR TITLE
Feature/officers summary

### PR DESCRIPTION
**Pull request by turowicz**
add officers endpoint as new client

### CODE REVIEW

**Comment by turowicz** [comment]
@kevbite have a look please, it resolves #13

**Comment by kevbite** [comment]
@Blundell89 as discussed, do you mind looking over this PR for me and merge it in if everything is ok?

**Comment by Blundell89** [comment]
No problem, just having a look over it now :)

**Comment by turowicz** [comment]
@Blundell89 let me know what you think, I am currently blocked and in dire need of this PR to be merged :)

**Comment by Blundell89** [comment]
Hey @turowicz, looks good. Would you mind bumping the version to 1.4.0 and I'll merge. Thanks

**Comment by turowicz** [comment]
roger @Blundell89

**Comment by turowicz** [comment]
done @Blundell89  :)

**Comment by Blundell89** [comment]
All done @turowicz, good stuff :+1:

**Pull request merged**
